### ISSUE TITLE
Should we add the other Drosophilid registrations and surfaces directly to this package?

### ISSUE THREAD

**Issue by ajdm** [jefferislab/nat.flybrains#24]
We could use the new git repository features to download the registrations instead, but there's currently no support (as far as I am aware) for downloading surface data. Would it be best to add the latter instead?

**Comment by jefferis** [comment]
I think we should add the surfaces and template objects directly. But adding all the registrations starts to get a bit heavy, so I think we should omit those.

**Comment by jefferis** [comment]
We should also ensure that docs for fetching additional registrations are OK.
