### ISSUE TITLE
JFRC2013 template brain

### ISSUE THREAD

**Issue by jefferis** [jefferislab/nat.flybrains#34]
This is now of particular interest as it is being used as the endpoint of a bridging registration to the FAFB whole adult brain EM volume. It is also widely used for light data at Janelia.

**Comment by ajdm** [comment]
This already exists in the package, no? ([DATA.r L209-L235](https://github.com/jefferislab/nat.flybrains/blob/master/R/DATA.r#L209-L235))

**Comment by jefferis** [comment]
Sorry this should have been a request for a mirroring registration not a template.

**Comment by ajdm** [comment]
Ah, okay, makes sense.

**Comment by ajdm** [comment]
Added in 1e3c80a0feeddec3b0bf5d888efcae8160354cca. It's not the best mirroring registration I've ever seen, but I think it's reasonable.

**Comment by jefferis** [comment]
Can you do a round trip comparison with the jfrc2 bridge/mirror to see if this is much worse?
